Use opencv-contrib-python-headless instead of opencv-python
According to https://pypi.org/project/opencv-contrib-python-headless/
under the section Installation and Usage, only one of:
- opencv-python
- opencv-contrib-python
- opencv-python-headless
- opencv-contrib-python-headless
can be specified. dl-core installs opencv-python from imagecorruptions
and opencv-contrib-python-headless from brtdevkit. These packages
step over each other in the cv2 namespace leading to error:
"module 'cv2.dnn' has no attribute 'DictValue'"

Since our python build system doesn't let us patch transitive
dependencies, we need to modify the source in this fork to use
a compatible opencv package.